"""Selectable text accompanying the translated lineup infographics."""
LINEUPS = [
 dict(name='Three Kingdoms · Deploy',hero='Lu Bu',avatar='lvbu',video='e1284rtzoq0',
  roster='Lu Bu, Cai Yan, Zhao Yun, Diaochan, Xiao Qiao, Zhou Yu, Cao Cao',
  logic='Cao Cao’s Prepare effect triggers Three Kingdoms heroes’ Deploy effects, steadily raising the team’s levels. Cai Yan adds levels when Three Kingdoms hero cards are played; Xiao Qiao adds more levels when allies trigger Deploy. Build a strong Lu Bu as your main carry.',
  tips=['Until you find Zhao Yun, Diaochan, and Zhou Yu, use other Three Kingdoms or Deploy heroes, such as Lady Zhen and Arke.','In the final rounds, use Last Will or Change of Commander to transfer another hero’s high level to Lu Bu.','Give Zhou Yu defensive equipment and a Mana Chalice so he survives and casts sooner.'],
  rounds=['Prioritize Sun Shangxiang; use Yi Xing or Niu Mo if needed. Reach tactician level 2 in round 2, then look for Cai Yan, Cao Cao, and Zhao Yun.','Complete Cai Yan, Cao Cao, Zhao Yun, and Diaochan. Reach level 3 after finding the core cards. Prioritize awakening Cao Cao and Cai Yan. If Change of Commander appears, buy two Sun Shangxiang cards. Reach level 4 and add Xiao Qiao.','Reach level 5 quickly and find Lu Bu and Zhou Yu. Deploy Lu Bu, transfer Sun Shangxiang’s levels with Change of Commander, then sell her to deploy Zhou Yu.','If the final battle looks uncertain, replace Zhao Yun with Taiyi Zhenren to revive Lu Bu.'],
  equipment=[('Lu Bu','Blazing Embrace, Infinity Edge, Red Demon'),('Cao Cao','Guardian’s Glory, Spirit Ward, Eye of the Phoenix')],
  tacticians=[('Bai Ge','Copies after every four combinations help awaken heroes. His Secret Technique can duplicate the cards you need.'),('Marco','Playing four tier 3 or lower hero cards earns treasure cards for resources or combat power. This suits the lineup’s many low-tier heroes.'),("Chang Xiao'e",'Her skill grants levels steadily. Wait until four heroes are deployed before using her Secret Technique.')],
  talents=[('Generosity','When your heroes trigger Deploy, two random Three Kingdoms heroes gain 2 levels.'),('Take Command','Receive a card that sets a Three Kingdoms hero’s level equal to the nearest other Three Kingdoms hero’s level.')]),
 dict(name='Sunset Sea · Prepare',hero='Angela',avatar='anqila',video='r1284pzl2o2',
  roster='Angela, Dolia, Biron, Allain, Milady, Athena, Heino',
  logic='Use the Prepare effects of Biron, Allain, Milady, and Angela with Dolia to grow your heroes and the Arcomia Core. Add Athena and Heino later to accelerate that growth. At combat start, the Core distributes its levels as Temporary Levels among Sunset Sea heroes; a single hero can receive at most 50% of the total. Athena’s Engage effect triggers allied Prepare effects.',
  tips=['Buy Ocean Treasure when it appears for faction equipment that improves damage and durability.','Against Flash heroes, surround Angela with allies to protect her.','For the deciding battle, consider keeping only Athena and one carry—Angela or Heino—among your Sunset Sea heroes, concentrating the Core’s levels on the carry.'],
  rounds=['Prioritize Biron to grow the Core and strengthen your early board. Reach level 2 in round 2.','Reach level 3 and buy Milady and Allain. Find Dolia and Angela, and awaken them to increase the team’s growth.','Reach level 5 and deploy Athena and Heino. Continue awakening heroes to strengthen their keyword effects and level the Core faster.','If you increase your deployment limit, add Ying to trigger Prepare and accelerate team and Core growth.'],
  equipment=[('Angela','Mana Chalice, Void Staff, Blazing Embrace'),('Athena','Overlord’s Armor, Guardian’s Glory, Eye of the Phoenix')],
  tacticians=[('Xiangxiang','Her attacks scale with your tier 1–3 heroes, making her a good fit for this low-tier lineup.'),("Chang Xiao'e",'Reliable level growth each round. Use her Secret Technique after deploying at least four heroes.'),('Naonao','If Sunset Sea is offered by her skill, choose it and use the skill each round to find your faction heroes faster.')],
  talents=[('Energy Siphon','When you sell a deployed hero, the Arcomia Core gains that hero’s levels.'),('Smart Armor','Receive random Sunset Sea equipment. An allied hero wearing it triggers Prepare one additional time.')]),
 dict(name='Riverlands · Totems',hero='Ao Yin',avatar='aoyin',video='b12847edijn',
  roster='Ao Yin, Consort Yu, Liang, Shao Siyuan, Guiguzi, Augran, Donghuang',
  logic='Guiguzi, Shao Siyuan, and Augran summon Seer, Destiny, and Afterlife Totems. Their levels grow with their summoners. More Totems give Ao Yin more Attack Speed and Temporary Levels during combat. Consort Yu and Liang add team levels. Donghuang protects the Totems and gains Temporary Levels from them. Seer provides healing, Destiny grants levels, and Afterlife helps the frontline absorb damage.',
  tips=['Ao Yin is the late-game carry. Surround him with heroes and Totems to protect him from backline attacks.','In the final rounds, replace Liang with Taiyi Zhenren to protect Ao Yin, or use Yaria with control equipment for extra safety.'],
  rounds=['Use Niu Mo and Gan & Mo early. Reach level 2 in round 3. These heroes are temporary and can be replaced when space is tight.','Reach level 3 quickly. Use free refreshes to find Consort Yu, Guiguzi, Liang, and Shao Siyuan. Give damage gear to Consort Yu. Once you have each of these heroes, reach level 4 and find Augran.','Reach level 5 and find Ao Yin, Donghuang, and Augran. Transfer Consort Yu’s damage equipment to Ao Yin.','Keep awakening your core heroes. Add Taiyi Zhenren if you have space, or another utility hero such as Yaria to suit the opponent.'],
  equipment=[('Ao Yin','Frostscar, Daybreaker, Nature Staff'),('Donghuang','Overlord’s Armor, Guardian’s Glory, Eye of the Phoenix')],
  tacticians=[('Xiangxiang','Her damage scales with the number and level of your tier 1–3 heroes.'),('Yaria','Her fawn shares frontline damage with Donghuang and prolongs battles, protecting a carry who grows stronger during combat.'),("Chang Xiao'e",'Her skill expands your level advantage, and her exclusive talent adds team stat bonuses.')],
  talents=[('Copier','Copy deployed heroes to awaken core cards faster.'),('Riverlands Reinforcements','Gain Riverlands heroes to complete the lineup sooner.')]),
 dict(name='Heluo · Ancient Coins',hero='Baili Xuance',avatar='bailixuance',video='e1284uuzil2',
  roster='Baili Xuance, Shangguan Wan’er, Dun Shan, Cheng Yaojin, Zhong Kui, Taiyi Zhenren, Li Yuanfang',
  logic='Li Yuanfang, Dun Shan, Cheng Yaojin, and Shangguan Wan’er generate Ancient Coins. Spend them on Baili Xuance to keep raising his level. Xuance also gains levels from the previous round’s kills. Zhong Kui lowers enemy levels, while Taiyi Zhenren provides a revive and gives Xuance more time to deal damage.',
  tips=['Prioritize equipment on Xuance to support both damage and survival. Spreading resources too thin weakens your carry.','Place Li Yuanfang and Taiyi Zhenren next to Xuance so their coins and revive reach him.','In the deciding rounds, adjust Xuance’s Flash position to target the enemy carry directly.'],
  rounds=['Buy Li Yuanfang or Yi Xing for early strength. Reach level 2 in round 3 and find Xuance. Pick up Dun Shan and use his Ancient Coins on Xuance.','Reach level 3, refresh the shop, and try to awaken Xuance. Find Cheng Yaojin and Zhong Kui for frontline strength and control.','Reach level 4 and find Shangguan Wan’er and Taiyi Zhenren. Reach level 5 before round 11. Awaken deployed heroes to improve the board.','Keep finding equipment for Xuance and awakening your heroes. If Xuance is not strong enough, consider Last Will or Transmute to move levels to Li Xin or Mulan.'],
  equipment=[('Baili Xuance','Infinity Edge, Blazing Embrace, Shadowfang'),('Cheng Yaojin','Spirit Crystal, Eye of the Phoenix, Ominous Premonition')],
  tacticians=[('Director Jiang','Playing hero or effect cards levels his chosen hero. At maximum tactician level, he also provides physical and magical lifesteal, suiting a single-carry lineup.'),("Chang Xiao'e",'Steady skill-based levels combine with Ancient Coins to strengthen Xuance.'),('Naonao','Choosing Heluo speeds up finding the lineup and saves Energy on searching.')],
  talents=[('Blink Chain','When a Flash hero defeats an enemy, it immediately blinks to the nearest enemy and is invulnerable for 0.5 seconds.'),('Slight Advantage','Gain 22% Critical Chance and 11% physical and magical lifesteal.')]),
 dict(name='Conquest · Tactics Cards',hero='Meng Ya',avatar='mengya',video='n128461rlih',
  roster='Meng Ya, Mi Yue, Xi Shi, Bai Qi, Old Master, Zhuang Zhou, Luban No. 7',
  logic='Xi Shi, Bai Qi, Old Master, Zhuang Zhou, and Luban No. 7 generate Tactics Cards. Playing effect cards triggers Mi Yue, who grants levels to your Conquest hero with the most equipment. Keep that hero as Meng Ya and keep playing cards to grow your main carry.',
  tips=['Mi Yue targets the Conquest hero with the most equipment. Ensure Meng Ya has more equipment than everyone else so another hero does not receive the levels.','If there is no spare deployment slot in the final rounds, sell Old Master and add Taiyi Zhenren to protect Meng Ya.','Give Meng Ya priority on effect cards, equipment, and other resources to build combat power quickly.'],
  rounds=['Use Yi Xing early. Reach level 2 in round 2 and prioritize finding Mi Yue.','Reach level 3 and collect Mi Yue, Xi Shi, Old Master, and Bai Qi. Awaken Mi Yue, then reach level 4. If you cannot awaken her, avoid staying at a low level so long that you fall behind.','Reach level 5 quickly and find Meng Ya, Zhuang Zhou, and Luban No. 7. Awaken Mi Yue, Xi Shi, and Bai Qi first to produce more Tactics Cards, then the other three.','Continue awakening heroes and searching for Meng Ya and Luban No. 7. With spare slots, add Taiyi Zhenren or Hai Yue for utility and safety.'],
  equipment=[('Meng Ya','Infinity Edge, Blazing Embrace, Mana Chalice'),('Bai Qi','Overlord’s Armor, Eye of the Phoenix, Ominous Premonition')],
  tacticians=[('Bai Ge','Old Master and Luban No. 7 generate Tactics Cards through combinations. Bai Ge provides hero copies for more combinations and more Tactics Cards.'),('Little Daji','Provides more effect cards and additional triggers, helping Mi Yue raise hero levels.'),('Naonao','Choose Conquest if offered to find heroes without spending so much Energy refreshing. At maximum level, choose a faction talent to strengthen the board.')],
  talents=[('Spring Rain','Receive a copy of a deployed Conquest hero; receive two if you won the battle.'),('Swift Orders','Receive one Tactics Card. At tactician level 5, it is guaranteed to be an advanced Tactics Card.')])
]

CARD_EFFECTS = [
 [('Lu Bu', 'Engage: The three highest-level Three Kingdoms heroes gain 20% physical and magical lifesteal. Double this effect for Lu Bu.'),
  ('Zhao Yun', 'Deploy: This hero and two random other heroes gain 1 level.'),
  ('Cao Cao', 'Prepare: Trigger one random Three Kingdoms hero’s Deploy effect.'),
  ('Cai Yan', 'Whenever you play a Three Kingdoms hero card, the three lowest-level Three Kingdoms heroes gain 1 level.'),
  ('Diaochan', 'Deploy: All Three Kingdoms heroes gain 1 level.'),
  ('Xiao Qiao', 'Whenever an allied hero triggers Deploy, three random allied heroes gain 1 level.'),
  ('Zhou Yu', 'Deploy: All allied heroes gain 1 level.')],
 [('Angela', 'Prepare: This hero and the Arcomia Core gain 2 levels.'),
  ('Biron', 'Prepare: The Arcomia Core gains 2 levels.'),
  ('Allain', 'Prepare: One Sunset Sea hero with the most equipment gains 2 levels. The Arcomia Core gains 1 level.'),
  ('Milady', 'Summons gain 3 temporary levels. Prepare: Double this temporary level bonus; the Arcomia Core gains 3 additional levels.'),
  ('Dolia', 'Whenever an allied hero triggers Prepare, three random allied heroes and the Arcomia Core gain 1 level.'),
  ('Athena', 'Engage: Trigger two random Sunset Sea heroes’ Prepare effects.'),
  ('Heino', 'Whenever the Arcomia Core gains levels, this hero gains 1 level.')],
 [('Ao Yin', 'In combat, each Totem grants Ao Yin 16% Attack Speed and 4 Temporary Levels every 4 seconds.'),
  ('Consort Yu', 'Engage: For each Totem on the field, this hero and two random other Riverlands heroes gain 1 level.'),
  ('Guiguzi', 'While deployed, summon a Seer Totem.'),
  ('Shao Siyuan', 'While deployed, summon a Destiny Totem.'),
  ('Liang', 'Whenever an allied unit triggers Engage, the three highest-level allies on the field permanently gain 1 level.'),
  ('Augran', 'While deployed, summon an Afterlife Totem. Whenever you trigger Prepare, the Afterlife Totem permanently gains 50% of its summoner’s Attack.'),
  ('Donghuang', 'Totems cannot be attacked first. Engage: Gain Temporary Levels equal to 15% of each Totem’s level.')],
 [('Baili Xuance', 'Flash. Prepare: For each enemy hero defeated by your Flash heroes last round, one random Flash hero gains 1 level.'),
  ('Li Yuanfang', 'Prepare: Use one Ancient Coin on the nearest Heluo hero.'),
  ('Dun Shan', 'Combine: Gain one Ancient Coin.'),
  ('Cheng Yaojin', 'Prepare: Gain one Ancient Coin and use one Ancient Coin on this hero.'),
  ('Zhong Kui', 'This hero and the allied hero to the right gain Double Strike. Double Strike: Attacks lower the target’s level by 10% (once per battle).'),
  ('Taiyi Zhenren', 'Engage: Grant Revive to the nearest allied hero.'),
  ('Shangguan Wan’er', 'Prepare: Use one Ancient Coin on each of three random Heluo heroes.')],
 [('Meng Ya', 'Deploy: Receive one Special Training Tactics Card.'),
  ('Mi Yue', 'Whenever you play an effect card, the Conquest hero with the most equipment gains 1 level.'),
  ('Xi Shi', 'Prepare: Receive one Wave Tactics Card.'),
  ('Bai Qi', 'The first time you play an effect card each round, receive one Fortress Tactics Card.'),
  ('Old Master', 'The first time you trigger Combine each round, receive one Provocation Tactics Card.'),
  ('Zhuang Zhou', 'Deploy: Gain 2 levels and receive one Demolition Tactics Card.'),
  ('Luban No. 7', 'Whenever your heroes combine three times, receive one random Tactics Card.')]
]

